name: Top Dog Groomers
favicon: null
layout_spectrum: 1
typography_spectrum: 0.1979408990591764
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FCFBE5'
    - '#EAEE25'
    - '#D918E3'
    - '#34D8E4'
    - '#FC1A1E'
  brandStrength: 0.5
  lightness: 0.236534669296816
  saturation: 0.05064384336583316
  rhythmicContrast: 0.203498174669221
purpose: []
