name: Top Dog Groomers
favicon: null
layout_spectrum: 0.37478321767412126
typography_spectrum: 0.19794089905917645
title: Top Dog Groomers Peluqueria Canina
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.007517962483689189
  lightness: 0.236534669296816
  saturation: 0.05064384336583316
  rhythmicContrast: 0.20349817466922104
purpose: []
