typography_spectrum: 0.3725820172112435
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.5729968824889511
  lightness: 0.9821659373119473
  saturation: 0.5470671411603689
  rhythmicContrast: 0.7278565231245011
github: true
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/0368b32d-65bf-49d3-90b2-a772c6424ee1.jpg
  type: Facebook
  appId: '355739404513850'
layout_spectrum: 0.24145477241836488
analytics:
  google: null
  facebook: null
  twitter: null
logo: null
name: Top Dog Groomers
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: ' Peluqueria Canina'
description: Top Dog Groomers
purpose:
  - type: contact
    url: 'tel:670 75 75 75'
    label: Call 670 75 75 75
