name: Top Dog Groomers
favicon: null
layout_spectrum: 0.5559
typography_spectrum: 0.77212
title: Top Dog Groomers Peluqueria Canina
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b600fa'
    - '#009dfc'
    - '#000000'
    - '#ff7b00'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
